### ISSUE TITLE
Feature sequences

### ISSUE THREAD

**Issue by kimkj38** [zhigangjiang/LGT-Net#4]
Hello, I'm confused about token size because it's square(8x8 or 16x16) on ViT.

As I understand, feature sequence means 256 tokens with 1024 dimension vector.
And $N/N_w(=256/16)$ window feature sequences of Window Block means that there're 16 partitions with 16 sequences per partition.

![스크린샷 2022-07-04 오전 10 03 43](https://user-images.githubusercontent.com/76815825/177064795-c3b68f8f-8a21-4003-b2f4-872d924527b5.png)

Then 4 partitions of this figure is just for simplification? Or did I get it wrong?

**Comment by zhigangjiang** [comment]
Yes,  for simplicity, this figure shows the case of $N_w=N/4$.

**Comment by kimkj38** [comment]
@zhigangjiang Thanks for your reply!
