### ISSUE TITLE
Preprocessing questions

### ISSUE THREAD

**Issue by Lu-Jichen** [zhigangjiang/LGT-Net#5]
Hi, I am interested in your work and trying to reproducing it.
I noticed that during the preprocessing there are 2 stages, and at each one you can resize the image, or resize it later using PIL.Image. So I wonder what is the correct way to resize the image to 512x1024, since there is slight difference with different resize method.

**Comment by zhigangjiang** [comment]
We didn't resize during preprocessing, we just resize once when we read the image. If you want to reproduce the training and evaluation results, I recommend using the resize method provided by OpenCV for consistency.
https://github.com/zhigangjiang/LGT-Net/blob/bb3f8881b1fc98f262d8c58a8b1fbcc009e83096/dataset/communal/read.py#L19

In addition, we used resize method of PIL in inference, which should not matter. We believe that the model should be robust to the differences brought by resize method.
https://github.com/zhigangjiang/LGT-Net/blob/bb3f8881b1fc98f262d8c58a8b1fbcc009e83096/inference.py#L183

**Comment by Lu-Jichen** [comment]
Thank your for your reply, I will try it. 
Besides, do I need to change the hyperparameters of mp3d.yaml, is that consistent with the checkpoint you provide on Matterport 3D?

**Comment by zhigangjiang** [comment]
You do not need to modify the yaml file.
