### ISSUE TITLE
Test sample error

### ISSUE THREAD

**Issue by Lu-Jichen** [zhigangjiang/LGT-Net#6]
Thank you for your previous reply! 
During evaluation of the trained model there is another issue, that is the uNb9QFRL6hY_5fc8f0e230eb49eca81fdfb0398d824b sample will raise an error for wrong depth length, I am not sure is that caused by the label annotation or the dataloader code. I would like to know have you met that problem before or there is something wrong in my evaluation process. I have also tried the checkpoint on the Github but there is still the same error.

**Comment by zhigangjiang** [comment]
You can paste the error informations here.

**Comment by zhigangjiang** [comment]
If we use the annotation of this sample uNb9QFRL6hY_5fc8f0e230eb49eca81fdfb0398d824b from https://github.com/ericsujw/Matterport3DLayoutAnnotation/blob/master/label_data.zip, Its points are shown below:
<img width="852" alt="Screen Shot 2022-10-21 at 16 21 30" src="https://user-images.githubusercontent.com/29976583/197148821-116a8c31-67f9-4ae0-bca8-0ccf44096318.png">

The camera center(x=0, z=0) is located outside the annotated points:
![myplot](https://user-images.githubusercontent.com/29976583/197148239-056c36f3-c808-4e63-9c8f-1067f0bef5eb.png)

---

So we use  the annotation from https://github.com/fuenwang/LayoutMP3D,  Its points are shown below:
<img width="925" alt="Screen Shot 2022-10-21 at 17 35 08" src="https://user-images.githubusercontent.com/29976583/197165317-d970b6b3-2d73-4020-a7c7-751d77e1a2b4.png">

![myplot](https://user-images.githubusercontent.com/29976583/197165507-562a2534-f42f-434f-b8e8-321282e583c5.jpg)

![uNb9QFRL6hY_5fc8f0e230eb49eca81fdfb0398d824b_boundary](https://user-images.githubusercontent.com/29976583/197115218-c6812754-b936-4a4b-9531-584782abdebc.png)

It was correct, so we replaced the label file for this sample.

**Comment by Lu-Jichen** [comment]
I think that is the reason of the error, thank you for your detailed explanation!
