### ISSUE TITLE
Looking for the dataset used

### ISSUE THREAD

**Issue by Kaushalsingh79** [zhigangjiang/LGT-Net#7]
Hello, a student here looking for the dataset used in the paper; can you provide the links, please?

**Comment by zhigangjiang** [comment]
You can directly download our processed mp3d dataset in [here](https://drive.google.com/file/d/1rEWXy5zHVozHC0hKHsuHTxchrNHfYoJ4/view?usp=sharing) (stitched skybox images and aligned vanishing points, size: 1.25 GB).

https://github.com/zhigangjiang/LGT-Net/issues/6#issuecomment-1279881945

**Comment by Kaushalsingh79** [comment]
Thank you so much
