### ISSUE TITLE
生成的3d模型会有缝隙

### ISSUE THREAD

**Issue by starinskycc** [zhigangjiang/LGT-Net#8]
![image](https://user-images.githubusercontent.com/6244330/224609056-9cbd56f8-8690-402a-92ec-4e951d19b1f4.png)
如上图所示

**Comment by zhigangjiang** [comment]
目前方式确实会有这个问题。

你可以尝试根据墙角坐标得到多个矩形，然后三角化计算Mesh，使用贴图方式。
这样生成的模型可以解决缝隙问题并且3D模型文件应该也更小。

如果时间允许我将会实现上述方式导出3D模型文件。

**Comment by starinskycc** [comment]
国我有款软件 everpano，用的技术和这个类似吗？
